/**
 * Cross-language interoperability tests using the canonical ACE test vectors.
 *
 * `spec/test-vectors.json` (→ `ace-spec/test-vectors.json`) is generated by
 * `spec/generate-vectors.py` from deterministic seed keys and shared across all
 * SDKs (TypeScript, Python, Swift) to guarantee wire-format compatibility for
 * identity derivation, X-Wing KEM, conversationId, signData, signatures and a
 * full encrypted message envelope.
 */
import { describe, it, expect, vi, afterEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { bytesToHex, hexToBytes } from '@noble/hashes/utils.js';
import { SoftwareIdentity, toBase64, fromBase64 } from '../src/identity.js';
import {
  computeConversationId,
  getACEKemSalt,
  kemPublicKeyFromSeed,
  kemDecapsulate,
} from '../src/encryption.js';
import { buildSignData, encodePayload, verifySignature, decodeSignature, encodeSignature } from '../src/signing.js';
import { parseMessage } from '../src/messages.js';
import { ThreadStateMachine } from '../src/state-machine.js';
import { ReplayDetector } from '../src/security.js';
import type { ACEMessage, SigningScheme } from '../src/types.js';

interface AgentVector {
  scheme: SigningScheme;
  signingPrivateKey: string;
  encryptionPrivateKey: string; // Base64 32-byte X-Wing seed
  signingPublicKey: string;
  encryptionPublicKey: string; // Base64 1216-byte X-Wing public key
  address: string;
  aceId: string;
}

interface Vectors {
  version: string;
  agents: Record<'alice' | 'bob', AgentVector>;
  xwing: {
    seed: string;
    publicKey: string;
    ciphertext: string;
    sharedSecret: string;
  };
  vectors: {
    aceKemSalt: string;
    conversationId: string;
    signData: {
      action: string;
      aceId: string;
      timestamp: number;
      messagePayload: {
        type: string;
        to: string;
        conversationId: string;
        messageId: string;
        threadId: string;
        kemCiphertext: string;
        ciphertext: string;
      };
      signDataHex: string;
    };
    signature: {
      scheme: string;
      signDataHex: string;
      signatureValue: string;
    };
    encryptedMessage: {
      from: 'alice' | 'bob';
      to: 'alice' | 'bob';
      envelope: ACEMessage;
      expectedBody: Record<string, unknown>;
    };
  };
}

function loadVectors(): Vectors {
  const path = new URL('../../spec/test-vectors.json', import.meta.url);
  return JSON.parse(readFileSync(path, 'utf8'));
}

function identityFrom(a: AgentVector): SoftwareIdentity {
  return SoftwareIdentity.fromExport({
    scheme: a.scheme,
    signingPrivateKey: a.signingPrivateKey,
    encryptionPrivateKey: a.encryptionPrivateKey,
  });
}

describe('Cross-Language Interop Vectors (V1)', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  it('test-vectors.json exists and loads', () => {
    const v = loadVectors();
    expect(v.version).toBe('1.0');
    expect(v.xwing).toBeDefined();
    expect(v.vectors.encryptedMessage).toBeDefined();
  });

  it('ACE KEM salt matches cross-language vector', () => {
    const v = loadVectors();
    expect(bytesToHex(getACEKemSalt())).toBe(v.vectors.aceKemSalt);
  });

  it('X-Wing draft-11 vector 1: keygen and decapsulate', () => {
    const { xwing } = loadVectors();
    const seed = hexToBytes(xwing.seed);
    expect(seed).toHaveLength(32);
    expect(bytesToHex(kemPublicKeyFromSeed(seed))).toBe(xwing.publicKey);
    expect(hexToBytes(xwing.publicKey)).toHaveLength(1216);
    expect(hexToBytes(xwing.ciphertext)).toHaveLength(1120);
    expect(bytesToHex(kemDecapsulate(hexToBytes(xwing.ciphertext), seed))).toBe(xwing.sharedSecret);
  });

  it('Alice (ed25519) identity derivation', () => {
    const v = loadVectors();
    const a = v.agents.alice;
    expect(a.scheme).toBe('ed25519');
    expect(fromBase64(a.encryptionPrivateKey)).toHaveLength(32);
    const alice = identityFrom(a);

    expect(alice.getACEId()).toBe(a.aceId);
    expect(alice.getAddress()).toBe(a.address);
    expect(toBase64(alice.getSigningPublicKey())).toBe(a.signingPublicKey);
    expect(alice.getEncryptionPublicKey()).toHaveLength(1216);
    expect(toBase64(alice.getEncryptionPublicKey())).toBe(a.encryptionPublicKey);
  });

  it('Bob (secp256k1) identity derivation', () => {
    const v = loadVectors();
    const b = v.agents.bob;
    expect(b.scheme).toBe('secp256k1');
    expect(fromBase64(b.encryptionPrivateKey)).toHaveLength(32);
    const bob = identityFrom(b);

    expect(bob.getACEId()).toBe(b.aceId);
    expect(bob.getAddress()).toBe(b.address);
    expect(toBase64(bob.getSigningPublicKey())).toBe(b.signingPublicKey);
    expect(bob.getEncryptionPublicKey()).toHaveLength(1216);
    expect(toBase64(bob.getEncryptionPublicKey())).toBe(b.encryptionPublicKey);
  });

  it('conversationId matches cross-language vector', () => {
    const v = loadVectors();
    const aliceEnc = fromBase64(v.agents.alice.encryptionPublicKey);
    const bobEnc = fromBase64(v.agents.bob.encryptionPublicKey);

    expect(computeConversationId(aliceEnc, bobEnc)).toBe(v.vectors.conversationId);
    // Symmetric: B↔A == A↔B
    expect(computeConversationId(bobEnc, aliceEnc)).toBe(v.vectors.conversationId);
  });

  it('signData matches cross-language vector', () => {
    const v = loadVectors();
    const sd = v.vectors.signData;
    const mp = sd.messagePayload;

    const kemCiphertext = fromBase64(mp.kemCiphertext);
    expect(kemCiphertext).toHaveLength(1120);
    const messagePayload = encodePayload(
      mp.type, mp.to, mp.conversationId, mp.messageId, mp.threadId,
      kemCiphertext,
      fromBase64(mp.ciphertext),
    );
    const signData = buildSignData(sd.action, sd.aceId, sd.timestamp, messagePayload);

    expect(bytesToHex(signData)).toBe(sd.signDataHex);
  });

  it('ed25519 signature verification against cross-language vector', () => {
    const v = loadVectors();
    const sigV = v.vectors.signature;
    const alice = v.agents.alice;

    const signData = hexToBytes(sigV.signDataHex);
    const sigBytes = decodeSignature(sigV.signatureValue, 'ed25519');
    const pubKey = fromBase64(alice.signingPublicKey);

    expect(verifySignature(signData, sigBytes, 'ed25519', pubKey)).toBe(true);
  });

  it('Alice signs and TS-produced signature verifies', async () => {
    const v = loadVectors();
    const alice = identityFrom(v.agents.alice);

    const signData = hexToBytes(v.vectors.signData.signDataHex);
    const { signature, scheme } = await alice.sign(signData);
    expect(scheme).toBe('ed25519');

    // Verify TS-produced signature matches the Python-produced one
    // (ed25519 is deterministic in @noble/curves — no synthetic randomness)
    expect(encodeSignature(signature, 'ed25519')).toBe(v.vectors.signature.signatureValue);
  });

  it('Python-produced encrypted message parses, verifies and decrypts as the recipient', async () => {
    const v = loadVectors();
    const em = v.vectors.encryptedMessage;
    const sender = identityFrom(v.agents[em.from]);
    const receiver = identityFrom(v.agents[em.to]);

    expect(em.envelope.from).toBe(sender.getACEId());
    expect(em.envelope.to).toBe(receiver.getACEId());
    expect(fromBase64(em.envelope.encryption.kemCiphertext)).toHaveLength(1120);

    // The envelope's timestamp is fixed; pin the clock so freshness passes.
    vi.useFakeTimers();
    vi.setSystemTime(new Date(em.envelope.timestamp * 1000));

    const parsed = await parseMessage(em.envelope, receiver, sender.getSigningPublicKey(), {
      stateMachine: new ThreadStateMachine(),
      replayDetector: new ReplayDetector(),
      expectedScheme: sender.getSigningScheme(),
      senderEncryptionPubKey: sender.getEncryptionPublicKey(),
    });

    expect(parsed.body).toEqual(em.expectedBody);
    expect(parsed.conversationId).toBe(v.vectors.conversationId);
  });
});
